# Generated by Django 5.2.1 on 2025-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
